v.'' = '~/cfg/nvim/init.lua'
v.n = '~/cfg/hm/app/nvim.nix'
v.l = { cd = '~/cfg/nvim/lib', vi = '~/cfg/nvim/lib/src/lib.rs' }

hm.'' = '~/cfg/hm/mod.nix'
hm.sh = '~/cfg/hm/sh/mod.nix'

git.'' = '~/cfg/git/config.ini'
git.n = '~/cfg/hm/app/git.nix'

os = '~/cfg/os/mod.nix'
mx = '~/cfg/tmux/tmux.conf'
bat = '~/cfg/bat/config'
ssh = '~/cfg/ssh/thaumy.conf'
cfg = '~/cfg/rsbin/edit-config/config.toml'
mpv = '~/cfg/mpv/input.conf'
dae = '~/cfg/dae/cfg.dae'
shf = '~/cfg/sh-history-filter/cfg.toml'
mako = '~/cfg/mako/config'
btop = '~/cfg/btop/btop.conf'
fish = '~/cfg/fish/interactive.fish'
dimf = '~/cfg/dup-img-finder/cfg.toml'
hypr = { cd = '~/cfg/hypr', vi = '~/cfg/hypr/hyprland/hyprland.conf' }
flake = '~/cfg/flake.nix'
rsbin = '~/cfg/rsbin/flake.nix'
cargo = '~/cfg/cargo/config.toml'
waybar = '~/cfg/waybar/config.json'
alacritty = '~/cfg/alacritty/config.toml'
